// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ERr_v_SF9knN-4vJQoY9q53FNgs6z1E',
    appId: '1:173072875898:web:2e2c588f7d7d59a00596c3',
    messagingSenderId: '173072875898',
    projectId: 'tp-2-2ab00',
    authDomain: 'tp-2-2ab00.firebaseapp.com',
    storageBucket: 'tp-2-2ab00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-x7ffdzF9umBTxeAQ5gMSMb5Kor5Qljg',
    appId: '1:173072875898:android:b38fc63929b5c4530596c3',
    messagingSenderId: '173072875898',
    projectId: 'tp-2-2ab00',
    storageBucket: 'tp-2-2ab00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVH_kM4Mf1AKLEMVzb6zuEGlpjgEHup0A',
    appId: '1:173072875898:ios:cb9b1c6247198f7c0596c3',
    messagingSenderId: '173072875898',
    projectId: 'tp-2-2ab00',
    storageBucket: 'tp-2-2ab00.firebasestorage.app',
    iosBundleId: 'com.example.tpMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVH_kM4Mf1AKLEMVzb6zuEGlpjgEHup0A',
    appId: '1:173072875898:ios:cb9b1c6247198f7c0596c3',
    messagingSenderId: '173072875898',
    projectId: 'tp-2-2ab00',
    storageBucket: 'tp-2-2ab00.firebasestorage.app',
    iosBundleId: 'com.example.tpMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ERr_v_SF9knN-4vJQoY9q53FNgs6z1E',
    appId: '1:173072875898:web:1d39f4d795b1421c0596c3',
    messagingSenderId: '173072875898',
    projectId: 'tp-2-2ab00',
    authDomain: 'tp-2-2ab00.firebaseapp.com',
    storageBucket: 'tp-2-2ab00.firebasestorage.app',
  );
}
